apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeulerwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openeulerwebsite
  template:
    metadata:
      labels:
        app: openeulerwebsite
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: openeulersvcsecret
      - name: configmap-volume
        configMap:
          name: openeulersvcconfigmap
      containers:
      - name: website
        image: openeuler/website:1.0
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
