apiVersion: v1
kind: Service
metadata:
  name: openeulersvc
  labels:
    app: openeuler
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: openeuler
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openeulerwebsite
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openeuler
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: openeulersvcsecret
      - name: configmap-volume
        configMap:
          name: openeulersvcconfigmap
      containers:
      - name: website
        image: openeuler/website:1.0
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
